/**
 * Shown wherever Merit produces AI-generated petition or outreach content.
 *
 * Merit drafts narratives against the USCIS O-1A criteria. It is a document
 * preparation tool, not a law firm, and it must never read as though it is
 * one.
 */

interface LegalDisclaimerProps {
  className?: string;
}

export const DISCLAIMER_TEXT =
  "This content is generated by AI from the evidence you entered. Merit is a " +
  "document preparation tool, not a law firm, and this is not legal advice. " +
  "No immigration outcome is guaranteed. Have a licensed immigration attorney " +
  "review your petition before you file.";

export function LegalDisclaimer({ className = "" }: LegalDisclaimerProps) {
  return (
    <p
      role="note"
      className={`text-xs leading-relaxed text-neutral-600 ${className}`}
    >
      {DISCLAIMER_TEXT}
    </p>
  );
}
